//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gfi_test_landing
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisplayComponent
    {
        public int id_component { get; set; }
        public int id_project { get; set; }
        public string visible { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual Project Project { get; set; }
    }
}
