//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gfi_test_landing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testLandingEntities : DbContext
    {
        public testLandingEntities()
            : base("name=testLandingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<ActionObject> ActionObject { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Attribute> Attribute { get; set; }
        public virtual DbSet<Battery> Battery { get; set; }
        public virtual DbSet<BatteryTest> BatteryTest { get; set; }
        public virtual DbSet<BatteryUser> BatteryUser { get; set; }
        public virtual DbSet<Component> Component { get; set; }
        public virtual DbSet<Credentials> Credentials { get; set; }
        public virtual DbSet<Data> Data { get; set; }
        public virtual DbSet<DisplayComponent> DisplayComponent { get; set; }
        public virtual DbSet<Environment> Environment { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Machine> Machine { get; set; }
        public virtual DbSet<Method> Method { get; set; }
        public virtual DbSet<Object> Object { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<ScheduleWeekDays> ScheduleWeekDays { get; set; }
        public virtual DbSet<Step> Step { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<TestAction> TestAction { get; set; }
        public virtual DbSet<TestUser> TestUser { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<WeekDays> WeekDays { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
