//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gfi_test_landing
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleWeekDays
    {
        public int id_schedule { get; set; }
        public int id_weekDays { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual WeekDays WeekDays { get; set; }
    }
}
