//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gfi_test_landing
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatteryUser
    {
        public string id_user { get; set; }
        public int id_battery { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Battery Battery { get; set; }
    }
}
