//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gfi_test_landing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string status { get; set; }
        public string id_user { get; set; }
        public Nullable<int> id_project { get; set; }
        public Nullable<int> id_batteryTest { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual BatteryTest BatteryTest { get; set; }
        public virtual Project Project { get; set; }
    }
}
